name: CI Practice

on:
  push:

    branches:
      - main
   pull_request:

    branches:
      - main

jobs:
  tests:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Run test
         run: |
           echo "GitHub Action is working"
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Branch: $GITHUB_REF_NAME"
